name: Build iOS IPA
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build web assets
        run: npm run build
      
      - name: Add iOS platform
        run: npx cap add ios
      
      - name: Sync iOS
        run: npx cap sync ios
      
      - name: Install CocoaPods dependencies
        run: |
          cd ios/App
          pod install
      
      - name: Build iOS IPA
        run: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -derivedDataPath build \
            -archivePath build/App.xcarchive \
            archive
          
          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath build/ipa
      
      - name: Upload IPA to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: ios/App/build/ipa/App.ipa
          retention-days: 30
      
      - name: Create Release
        if: success()
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0-ios-${{ github.run_number }}
          release_name: iOS Build v1.0.0 #${{ github.run_number }}
          body: |
            iOS IPA build for Apple App Store
            
            **Build Details:**
            - Run: ${{ github.run_number }}
            - Commit: ${{ github.sha }}
            - Branch: ${{ github.ref }}
            
            Download the IPA file from the artifacts section.
          draft: false
          prerelease: false
      
      - name: Upload Release Asset
        if: success()
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ios/App/build/ipa/App.ipa
          asset_name: grupo-estuda-v1.0.0.ipa
          asset_content_type: application/octet-stream
