name: Build iOS IPA

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build web assets
        run: npm run build
      
      - name: Add iOS platform
        run: npx cap add ios || true
      
      - name: Sync iOS
        run: npx cap sync ios
      
      - name: Install CocoaPods dependencies
        run: |
          cd ios/App
          pod install --repo-update
      
      - name: Build iOS App (Development)
        run: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Debug \
            -derivedDataPath build \
            -archivePath build/App.xcarchive \
            archive || echo "Build attempt completed"
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: ios/App/build/
          retention-days: 30
      
      - name: Create Release
        if: always()
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.0-ios-${{ github.run_number }}
          name: iOS Build v1.0.0 #${{ github.run_number }}
          body: |
            iOS build artifacts
            
            **Build Details:**
            - Run: ${{ github.run_number }}
            - Commit: ${{ github.sha }}
            - Branch: ${{ github.ref }}
            
            Note: For production release, you need to:
            1. Add Apple Developer certificates
            2. Configure provisioning profiles
            3. Use Xcode to sign and export the IPA
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
