// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const runtimeSupabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const runtimeSupabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Se não houver variáveis de ambiente, o app mostrará erro de conexão.
// É necessário configurar VITE_SUPABASE_URL e VITE_SUPABASE_ANON_KEY no arquivo .env
const SUPABASE_URL = runtimeSupabaseUrl || '';
const SUPABASE_PUBLISHABLE_KEY = runtimeSupabaseAnonKey || '';

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.warn('Supabase URL ou Anon Key não configurados. Verifique seu arquivo .env');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
